name: Build and Deploy Chatbot

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o código do seu repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Substitui o placeholder no arquivo
      - name: Substituir placeholder pela chave do secret
        run: |
          sed -i "s|%%OPENROUTER_API_KEY_PLACEHOLDER%%|${{ secrets.OPENROUTER_API_KEY }}|g" "js/chatbot.js"
        shell: bash

      # 3. PASSO NOVO: Faz um commit local das alterações para que a ação de deploy as veja
      - name: Commit dos arquivos modificados
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add js/chatbot.js
          git commit -m "Substituir chave de API para o deploy"
        shell: bash
      
      # 4. Faz o deploy do diretório atual, que agora inclui o commit com o arquivo modificado
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .