name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Mude para 'master' ou sua branch principal, se for diferente

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Replace API Key Placeholder
        env:
          OPENROUTER_API_KEY_1: ${{ secrets.OPENROUTER_API_KEY_1 }}
          OPENROUTER_API_KEY_2: ${{ secrets.OPENROUTER_API_KEY_2 }}
          OPENROUTER_API_KEY_3: ${{ secrets.OPENROUTER_API_KEY_3 }}
          OPENROUTER_API_KEY_4: ${{ secrets.OPENROUTER_API_KEY_4 }}
          OPENROUTER_API_KEY_5: ${{ secrets.OPENROUTER_API_KEY_5 }}
          OPENROUTER_API_KEY_6: ${{ secrets.OPENROUTER_API_KEY_6 }}
          OPENROUTER_API_KEY_7: ${{ secrets.OPENROUTER_API_KEY_7 }}
          OPENROUTER_API_KEY_8: ${{ secrets.OPENROUTER_API_KEY_8 }}
          OPENROUTER_API_KEY_9: ${{ secrets.OPENROUTER_API_KEY_9 }}
          OPENROUTER_API_KEY_10: ${{ secrets.OPENROUTER_API_KEY_10 }}
        run: |
          JS_FILE="js/main.js"
          API_KEYS=""
          
          if [[ -n "${{ env.OPENROUTER_API_KEY_1 }}" ]]; then API_KEYS+='"${{ env.OPENROUTER_API_KEY_1 }}"'; fi
          if [[ -n "${{ env.OPENROUTER_API_KEY_2 }}" ]]; then if [[ -n "$API_KEYS" ]]; then API_KEYS+=", "; fi; API_KEYS+='"${{ env.OPENROUTER_API_KEY_2 }}"'; fi
          if [[ -n "${{ env.OPENROUTER_API_KEY_3 }}" ]]; then if [[ -n "$API_KEYS" ]]; then API_KEYS+=", "; fi; API_KEYS+='"${{ env.OPENROUTER_API_KEY_3 }}"'; fi
          if [[ -n "${{ env.OPENROUTER_API_KEY_4 }}" ]]; then if [[ -n "$API_KEYS" ]]; then API_KEYS+=", "; fi; API_KEYS+='"${{ env.OPENROUTER_API_KEY_4 }}"'; fi
          if [[ -n "${{ env.OPENROUTER_API_KEY_5 }}" ]]; then if [[ -n "$API_KEYS" ]]; then API_KEYS+=", "; fi; API_KEYS+='"${{ env.OPENROUTER_API_KEY_5 }}"'; fi
          if [[ -n "${{ env.OPENROUTER_API_KEY_6 }}" ]]; then if [[ -n "$API_KEYS" ]]; then API_KEYS+=", "; fi; API_KEYS+='"${{ env.OPENROUTER_API_KEY_6 }}"'; fi
          if [[ -n "${{ env.OPENROUTER_API_KEY_7 }}" ]]; then if [[ -n "$API_KEYS" ]]; then API_KEYS+=", "; fi; API_KEYS+='"${{ env.OPENROUTER_API_KEY_7 }}"'; fi
          if [[ -n "${{ env.OPENROUTER_API_KEY_8 }}" ]]; then if [[ -n "$API_KEYS" ]]; then API_KEYS+=", "; fi; API_KEYS+='"${{ env.OPENROUTER_API_KEY_8 }}"'; fi
          if [[ -n "${{ env.OPENROUTER_API_KEY_9 }}" ]]; then if [[ -n "$API_KEYS" ]]; then API_KEYS+=", "; fi; API_KEYS+='"${{ env.OPENROUTER_API_KEY_9 }}"'; fi
          if [[ -n "${{ env.OPENROUTER_API_KEY_10 }}" ]]; then if [[ -n "$API_KEYS" ]]; then API_KEYS+=", "; fi; API_KEYS+='"${{ env.OPENROUTER_API_KEY_10 }}"'; fi

          JOINED_KEYS="${API_KEYS}"
          echo "Generated API Keys String: ${JOINED_KEYS}"
          
          echo "Attempting to replace placeholder in $JS_FILE"
          if [ -f "$JS_FILE" ]; then
            sed "s|/\*%%OPENROUTER_API_KEYS_ARRAY_PLACEHOLDER%%\*/|${JOINED_KEYS}|g" "$JS_FILE" > "$JS_FILE.tmp"
            mv "$JS_FILE.tmp" "$JS_FILE"
            
            echo "Placeholder replacement done."
            
            echo "--- Content of $JS_FILE after sed on runner: ---"
            cat "$JS_FILE"
            echo "--- End of content ---"
          else
            echo "Error: $JS_FILE not found!"
            exit 1
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # MUDANÇA CRÍTICA AQUI: Use uma lista YAML para os caminhos.
          # Cada item da lista é um caminho separado.
          path:
            - ./ 
            - ./css 
            - ./js 
            - ./data 
            - ./images 
            # Adicione outras pastas ou arquivos específicos se houver
            
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
