name: Build and Deploy Chatbot

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o código do seu repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # CORREÇÃO 1: Usa o caminho correto para o arquivo, sem a pasta "Chatbot-Eletroquimica"
      - name: Substituir placeholder pela chave do secret
        run: |
          sed -i "s|%%OPENROUTER_API_KEY_PLACEHOLDER%%|${{ secrets.OPENROUTER_API_KEY }}|g" "js/chatbot.js"
        shell: bash

      # CORREÇÃO 2: Publica o diretório raiz, que contém todos os seus arquivos
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .