name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Mude para 'master' ou sua branch principal, se for diferente

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Replace API Key Placeholder
        run: |
          JS_FILE="js/main.js"
          
          # A chave API única será lida do segredo OPENROUTER_API_KEY_FOR_PAGES
          API_KEY_VALUE="${{ secrets.OPENROUTER_API_KEY_FOR_PAGES }}"

          echo "Attempting to replace placeholder in $JS_FILE"
          if [ -f "$JS_FILE" ]; then
            # Substitui o placeholder de chave única no arquivo JavaScript
            # O placeholder esperado no JS é "%%OPENROUTER_API_KEY_PLACEHOLDER%%"
            sed "s|%%OPENROUTER_API_KEY_PLACEHOLDER%%|${API_KEY_VALUE}|g" "$JS_FILE" > "$JS_FILE.tmp"
            mv "$JS_FILE.tmp" "$JS_FILE"
            
            echo "Placeholder replacement done."
            
            echo "--- Content of $JS_FILE after sed on runner: ---"
            cat "$JS_FILE"
            echo "--- End of content ---"
          else
            echo "Error: $JS_FILE not found!"
            exit 1
          fi

      # Adiciona uma etapa para listar todos os arquivos recursivamente antes de fazer o upload
      - name: List files before upload (for debugging)
        run: |
          echo "--- Listing all files recursively before artifact upload: ---"
          ls -R .
          echo "--- End of file list ---"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Volta para o caminho simples '.' que deve incluir tudo na raiz e subdiretórios
          path: . 
            
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
