name: Build and Deploy Chatbot

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o código mais recente do seu repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Substitui o placeholder no arquivo usando 'sed'
      - name: Substituir placeholder pela chave do secret
        run: |
          echo "--> Tentando substituir a chave em js/chatbot.js"
          sed -i "s|%%OPENROUTER_API_KEY_PLACEHOLDER%%|${{ secrets.OPENROUTER_API_KEY }}|g" "js/chatbot.js"
          echo "--> Comando de substituição executado."
        shell: bash

      # 3. PASSO DE VERIFICAÇÃO CRUCIAL: Mostra as 5 primeiras linhas do arquivo APÓS a modificação
      - name: Verificar conteúdo do arquivo antes do deploy
        run: |
          echo "--> Verificando o conteúdo de js/chatbot.js para confirmar a substituição:"
          head -n 5 js/chatbot.js
        shell: bash

      # 4. Faz o deploy do diretório atual (que contém o arquivo modificado) para o GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .